version: "3.8"

services:
  web:
    build: .
    command: gunicorn secure_api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./secure_api/.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:6

volumes:
  postgres_data:
